<script setup>
import {ref,computed,watch} from 'vue';
import {wall,action,save,request,mediaUrl,getToken,logout,sceneSources,createId} from '../api';
import WallCanvas from './WallCanvas.vue';
import GooglePhotosGallery from './GooglePhotosGallery.vue';
const tab=ref('overview'),drawer=ref(false),busy=ref(false),notice=ref(''),query=ref(''),filter=ref('all'),sceneDialog=ref(false),editing=ref(null),widgetDialog=ref(false),widget=ref(null),optionsText=ref(''),secretText=ref('{}'),dialogError=ref(''),settings=ref(null),monitorDraft=ref([]),uploadInput=ref(),uploadTarget=ref(null);
const nav=[{id:'overview',label:'Übersicht',icon:'mdi-view-dashboard-outline'},{id:'media',label:'Mediathek',icon:'mdi-image-multiple-outline'},{id:'widgets',label:'Informationen',icon:'mdi-widgets-outline'},{id:'monitors',label:'Monitore',icon:'mdi-monitor-multiple'},{id:'settings',label:'Einstellungen',icon:'mdi-cog-outline'}];
const types=[{value:'stack',title:'Bilderstapel',icon:'mdi-image-multiple-outline'},{value:'panorama',title:'Scrollendes Panorama',icon:'mdi-panorama-horizontal-outline'},{value:'fit',title:'Passendes Bild',icon:'mdi-image-outline'},{value:'html',title:'HTML-Seite',icon:'mdi-code-tags'},{value:'google-photos',title:'Google-Photos-Galerie',icon:'mdi-google-photos'}];
const positions=[{title:'Oben links',value:'top-left'},{title:'Oben mittig',value:'top-center'},{title:'Oben rechts',value:'top-right'},{title:'Unten links',value:'bottom-left'},{title:'Unten mittig',value:'bottom-center'},{title:'Unten rechts',value:'bottom-right'}];
const seasons=[{title:'Frühling',value:'spring'},{title:'Sommer',value:'summer'},{title:'Herbst',value:'autumn'},{title:'Winter',value:'winter'}];
const widgetIcons={clock:'mdi-clock-outline',title:'mdi-format-title',weather:'mdi-weather-partly-cloudy',transit:'mdi-bus',school:'mdi-school-outline',mpd:'mdi-music-note-outline',calendar:'mdi-calendar-outline',cameras:'mdi-cctv',soccer:'mdi-soccer'};
const current=computed(()=>wall.config.scenes.find(s=>s.id===wall.state.currentId));
const scenes=computed(()=>wall.config.scenes.filter(s=>(filter.value==='all'||s.type===filter.value)&&`${s.title} ${s.category}`.toLowerCase().includes((query.value||'').toLowerCase())));
const activeWidgets=computed(()=>wall.config.widgets.filter(w=>w.enabled));
const clone=x=>JSON.parse(JSON.stringify(x));
watch(()=>tab.value,()=>{drawer.value=false;if(tab.value==='settings')settings.value=clone(wall.config);if(tab.value==='monitors')monitorDraft.value=clone(wall.config.monitors);});
async function commit(config,message='Gespeichert'){busy.value=true;try{await save(config);notice.value=message;return true;}catch(e){wall.error=e.message;return false;}finally{busy.value=false;}}
function editScene(s){editing.value=s?clone(s):{id:createId(),title:'Neue Szene',type:'fit',category:'Eigene Bilder',sources:[],enabled:true,weight:3,seasons:[],hours:[],scrollSeconds:90};dialogError.value='';sceneDialog.value=true;}
async function saveScene(){if(!editing.value.title.trim())return dialogError.value='Bitte einen Titel eingeben.';if(!editing.value.sources.length&&editing.value.type!=='google-photos')return dialogError.value='Bitte Bilder hochladen oder eine Quelle eingeben.';const config=clone(wall.config),index=config.scenes.findIndex(s=>s.id===editing.value.id);if(index<0)config.scenes.push(clone(editing.value));else config.scenes[index]=clone(editing.value);if(await commit(config,'Szene gespeichert')&&editing.value.type!=='google-photos')sceneDialog.value=false;}
async function deleteScene(){const config=clone(wall.config);config.scenes=config.scenes.filter(s=>s.id!==editing.value.id);if(await commit(config,'Szene entfernt'))sceneDialog.value=false;}
function chooseFiles(target){uploadTarget.value=target;uploadInput.value.click();}
async function upload(event){const files=[...event.target.files];event.target.value='';if(!files.length)return;busy.value=true;try{const data=new FormData();files.forEach(f=>data.append('files',f));const response=await request('/upload','POST',data);if(uploadTarget.value==='editing')editing.value.sources.push(...response.sources);else{editScene();editing.value.title=files[0].name.replace(/\.[^.]+$/,'');editing.value.type=/\.html?$/i.test(files[0].name)?'html':files.length>1?'stack':'fit';editing.value.sources=response.sources;}}catch(e){wall.error=e.message;}finally{busy.value=false;}}
function addWidget(){editWidget({id:createId(),title:'Vertretungsplan',type:'school',enabled:false,monitor:wall.config.monitors[0].id,position:'top-left',refreshSeconds:60,options:{rows:[]}});}
function editWidget(w){widget.value=clone(w);optionsText.value=JSON.stringify(w.options,null,2);secretText.value='{}';dialogError.value='';widgetDialog.value=true;}
async function saveWidget(){try{const options=JSON.parse(optionsText.value),secrets=JSON.parse(secretText.value);if(!options||Array.isArray(options)||typeof options!=='object')throw new Error('Optionen müssen ein JSON-Objekt sein.');widget.value.options=options;const config=clone(wall.config);const index=config.widgets.findIndex(w=>w.id===widget.value.id);if(index<0)config.widgets.push(clone(widget.value));else config.widgets[index]=clone(widget.value);if(await commit(config,'Informationsmodul gespeichert')){if(Object.keys(secrets).length)await request(`/secrets/${widget.value.id}`,'PUT',secrets);widgetDialog.value=false;}}catch(e){dialogError.value=e.message;}}
async function toggleWidget(w,value){const config=clone(wall.config);config.widgets.find(x=>x.id===w.id).enabled=value;await commit(config);}
function assignDisplay(m,id){const d=wall.displays.find(d=>d.id===id);m.displayId=id;if(d){m.width=d.bounds.width;m.height=d.bounds.height;m.x=d.bounds.x;m.y=d.bounds.y;}}
function addMonitor(){monitorDraft.value.push({id:createId(),name:`Monitor ${monitorDraft.value.length+1}`,displayId:null,x:monitorDraft.value.reduce((n,m)=>Math.max(n,m.x+m.width),0),y:0,width:1600,height:900,enabled:true});}
async function saveMonitors(){const config=clone(wall.config);config.monitors=clone(monitorDraft.value);if(new Set(config.monitors.filter(m=>m.displayId&&m.enabled).map(m=>m.displayId)).size!==config.monitors.filter(m=>m.displayId&&m.enabled).length){wall.error='Ein physischer Bildschirm kann nur einem Monitor zugeordnet werden.';return;}await commit(config,'Monitorlayout gespeichert');}
async function saveSettings(){await commit({...clone(wall.config),name:settings.value.name,intervalSeconds:Number(settings.value.intervalSeconds),fadeSeconds:Number(settings.value.fadeSeconds),brightness:Number(settings.value.brightness),shuffle:settings.value.shuffle});}
async function copyToken(){try{await navigator.clipboard.writeText(getToken());notice.value='Zugangscode kopiert';}catch{wall.error='Kopieren ist nur in einem sicheren Browserkontext verfügbar.';}}
function exportConfig(){const blob=new Blob([JSON.stringify(wall.config,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='monitor-wall-settings.json';a.click();URL.revokeObjectURL(url);}
async function importConfig(event){try{const file=event.target.files[0];if(file)await commit(JSON.parse(await file.text()),'Konfiguration importiert');}catch(e){wall.error=e.message;}finally{event.target.value='';}}
const sourceText=computed({get:()=>editing.value?.sources.join('\n')||'',set:v=>editing.value.sources=v.split('\n').map(s=>s.trim()).filter(Boolean)});
const optionHelp={weather:'latitude, longitude: Koordinaten des Ortes.',transit:'stop: Haltestelle; minMinutes: Mindestvorlauf; exclude: ausgeschlossene Ziele; limit: Anzahl.',school:'url: JSON-Endpunkt; class: Klasse. Alternativ rows: Texte oder Objekte mit date, class, lesson, subject, text.',mpd:'host, port: MPD-Server. Passwort unter Zugangsdaten speichern.',calendar:'calendarId, days: Google-Kalender. Zugangsdaten: clientId, clientSecret, refreshToken.',cameras:'cameras: [{"name":"Eingang","url":"http://kamera/snapshot.jpg"}]. Unterstützt JPEG/PNG und MJPEG.',soccer:'league: OpenLigaDB-Kürzel (z. B. bl1); season: Startjahr; team: optionaler Namensfilter.',clock:'Datum und Uhrzeit werden lokal dargestellt.',title:'Zeigt den Titel der aktiven Szene.'};
</script>
<template>
 <v-layout>
  <v-navigation-drawer :model-value="$vuetify.display.mdAndUp||drawer" @update:model-value="drawer=$event" :permanent="$vuetify.display.mdAndUp" width="252" class="sidebar">
   <a class="brand" href="/admin"><span class="brand-mark"><v-icon icon="mdi-view-dashboard-outline"/></span><span>monitor<span class="brand-light">wall</span><small>DEIN ZUHAUSE. IM BLICK.</small></span></a>
   <div class="nav-caption">ARBEITSPLATZ</div><v-list class="nav-list" nav><v-list-item v-for="item in nav" :key="item.id" :title="item.label" :prepend-icon="item.icon" :active="tab===item.id" color="primary" @click="tab=item.id"/></v-list>
   <template #append><div class="sidebar-bottom"><span class="status-dot" :class="{offline:!wall.connected}"></span>{{wall.connected?'Bilderwand verbunden':'Verbindung unterbrochen'}}<small>Alle Einstellungen werden lokal gespeichert.</small><v-btn variant="text" size="small" prepend-icon="mdi-logout" @click="logout">Abmelden</v-btn></div></template>
  </v-navigation-drawer>
  <v-main><div class="admin-content">
   <header class="topbar"><div class="d-flex align-center ga-3"><v-btn v-if="$vuetify.display.smAndDown" icon="mdi-menu" variant="text" aria-label="Navigation öffnen" @click="drawer=!drawer"/><span class="muted">Unser Zuhause</span><v-icon size="16" icon="mdi-chevron-right"/><span>{{nav.find(n=>n.id===tab)?.label}}</span></div><div class="d-flex align-center ga-3"><span class="connection-badge"><span class="status-dot" :class="{offline:!wall.connected}"/>{{wall.connected?'Live':'Offline'}}</span><v-avatar size="34" color="surface-variant"><v-icon size="19" icon="mdi-home-outline"/></v-avatar></div></header>
   <div class="page-heading"><div><div class="eyebrow">{{tab==='overview'?'ALLES AN EINEM ORT':'DEINE BILDERWAND'}}</div><h1>{{ {overview:'Schön, zu Hause zu sein.',media:'Momente, die bleiben.',widgets:'Das Wichtigste im Blick.',monitors:'Raum für deine Bilder.',settings:'Ganz nach deinem Rhythmus.'}[tab] }}</h1><p class="muted">{{ {overview:'Deine Bilder. Dein Alltag. Eine Wand voller Leben.',media:'Verwalte Bilderstapel, Panoramen und deine Lieblingsseiten.',widgets:'Platziere Informationen genau dort, wo du sie brauchst.',monitors:'Verbinde deine Bildschirme zu einer gemeinsamen Leinwand.',settings:'Passe Wiedergabe und Fernsteuerung an dein Zuhause an.'}[tab] }}</p></div><v-btn v-if="tab==='media'" color="primary" prepend-icon="mdi-plus" @click="editScene()">Szene hinzufügen</v-btn><v-btn v-else-if="tab==='widgets'" color="primary" prepend-icon="mdi-plus" @click="addWidget">Modul hinzufügen</v-btn><v-btn v-else-if="tab==='overview'" variant="outlined" prepend-icon="mdi-arrow-top-right" href="/wall" target="_blank">Bilderwand öffnen</v-btn></div>
   <template v-if="tab==='overview'">
    <section class="preview-card"><div class="section-top"><div class="d-flex align-center ga-3"><span class="live-tag">LIVE-VORSCHAU</span><span class="muted">{{wall.config.monitors.filter(m=>m.enabled).length}} Monitore · eine Leinwand</span></div><v-icon color="secondary" icon="mdi-monitor-multiple"/></div><WallCanvas preview class="dashboard-preview"/><div class="playback-bar"><div class="scene-caption"><span class="tiny-label">JETZT AUF DER BILDERWAND</span><strong>{{current?.title||'Keine aktive Szene'}}</strong><span class="muted">{{types.find(t=>t.value===current?.type)?.title}} <span v-if="current">· {{current.category}}</span></span></div><div class="playback-buttons"><v-btn icon="mdi-skip-previous" aria-label="Vorherige Szene" variant="text" @click="action('previous')"/><v-btn :icon="wall.state.paused?'mdi-play':'mdi-pause'" :aria-label="wall.state.paused?'Abspielen':'Pausieren'" color="primary" @click="action('pause')"/><v-btn icon="mdi-skip-next" aria-label="Nächste Szene" variant="text" @click="action('next')"/></div><div class="rotation-status"><span class="status-dot" :class="{offline:wall.state.paused}"/>{{wall.state.paused?'Wiedergabe pausiert':'Automatischer Bildwechsel'}}<small>Alle {{wall.config.intervalSeconds}} Sekunden</small></div></div></section>
    <div class="stat-grid"><div class="stat-card" v-for="stat in [{icon:'mdi-image-multiple-outline',value:wall.config.scenes.length,label:'Szenen in der Mediathek',sub:'Augenblicke für jeden Tag'},{icon:'mdi-monitor-multiple',value:wall.config.monitors.filter(m=>m.enabled).length,label:'Aktive Monitore',sub:`${wall.displays.length} physische Displays erkannt`},{icon:'mdi-widgets-outline',value:activeWidgets.length,label:'Informationsmodule',sub:'Dein Alltag auf einen Blick'}]" :key="stat.label"><v-icon :icon="stat.icon" color="secondary"/><div><strong>{{stat.value}}</strong><p>{{stat.label}}</p><small>{{stat.sub}}</small></div></div></div>
    <div class="overview-bottom"><section><div class="section-title"><h2>Deine Mediathek</h2><v-btn variant="text" color="primary" append-icon="mdi-arrow-right" @click="tab='media'">Alle Szenen</v-btn></div><div class="mini-scenes"><button v-for="s in wall.config.scenes.slice(0,3)" :key="s.id" class="mini-scene" :class="{selected:s.id===current?.id}" @click="action('select',s.id)"><img v-if="s.type!=='html'&&sceneSources(s)[0]" :src="mediaUrl(sceneSources(s)[0])" alt=""><div v-else class="scene-placeholder"><v-icon icon="mdi-code-tags"/></div><span>{{s.title}}</span><small>{{types.find(t=>t.value===s.type)?.title}}</small></button></div></section><section class="information-summary"><div class="section-title"><h2>Im Blick</h2><v-btn icon="mdi-arrow-top-right" variant="text" size="small" aria-label="Informationen verwalten" @click="tab='widgets'"/></div><div v-for="w in activeWidgets.slice(0,4)" :key="w.id" class="summary-row"><v-icon :icon="widgetIcons[w.type]" color="secondary"/><div><strong>{{w.title}}</strong><small>{{wall.config.monitors.find(m=>m.id===w.monitor)?.name}}</small></div><span class="module-status" :class="{error:wall.widgets[w.id]?.status==='error'}">{{wall.widgets[w.id]?.status==='error'?'Prüfen':'Aktiv'}}</span></div></section></div>
   </template>
   <template v-if="tab==='media'"><div class="media-toolbar"><v-text-field v-model="query" placeholder="Szenen durchsuchen …" prepend-inner-icon="mdi-magnify" hide-details clearable @click:clear="query=''"/><v-select v-model="filter" :items="[{title:'Alle Kategorien',value:'all'},...types]" hide-details/><v-btn variant="tonal" prepend-icon="mdi-upload" :loading="busy" @click="chooseFiles('new')">Bilder hochladen</v-btn></div><div class="media-grid"><v-card v-for="s in scenes" :key="s.id" class="media-card"><div class="media-image" @click="editScene(s)"><img v-if="sceneSources(s)[0]&&s.type!=='html'" :src="mediaUrl(sceneSources(s)[0])" alt=""><div v-else class="scene-placeholder"><v-icon size="56" :icon="types.find(t=>t.value===s.type)?.icon"/></div><span class="media-type">{{types.find(t=>t.value===s.type)?.title}}</span><span v-if="s.id===current?.id" class="media-current">Jetzt live</span></div><div class="pa-5"><div class="d-flex align-center justify-space-between"><h3>{{s.title}}</h3><v-btn size="small" icon="mdi-pencil-outline" variant="text" aria-label="Szene bearbeiten" @click="editScene(s)"/></div><p class="muted text-body-2">{{s.category}} · {{sceneSources(s).length}} {{s.type==='html'?'Seite(n)':'Bild(er)'}}</p><div class="d-flex justify-space-between align-center mt-4"><v-chip size="small" :color="s.enabled?'primary':undefined" variant="tonal">{{s.enabled?'Aktiv':'Deaktiviert'}}</v-chip><v-btn variant="text" color="primary" append-icon="mdi-play" :disabled="!s.enabled||!sceneSources(s).length" @click="action('select',s.id)">Anzeigen</v-btn></div></div></v-card></div><div v-if="!scenes.length" class="empty-state"><v-icon size="48" icon="mdi-image-plus-outline"/><h3>Platz für neue Erinnerungen</h3><p>Bilder hochladen oder eine neue Szene anlegen.</p></div></template>
   <template v-if="tab==='widgets'"><div class="widget-grid"><v-card v-for="w in wall.config.widgets" :key="w.id" class="pa-6"><div class="d-flex justify-space-between align-center"><div class="module-icon"><v-icon :icon="widgetIcons[w.type]"/></div><v-switch :model-value="w.enabled" hide-details color="primary" density="compact" :disabled="busy" :aria-label="`${w.title} aktivieren`" @update:model-value="v=>toggleWidget(w,v)"/></div><h3 class="mt-5">{{w.title}}</h3><p class="muted mt-2">{{wall.config.monitors.find(m=>m.id===w.monitor)?.name}} · {{positions.find(p=>p.value===w.position)?.title}}</p><div class="module-message mt-4">{{w.enabled?(wall.widgets[w.id]?.error||(['clock','title'].includes(w.type)?'Bereit':wall.widgets[w.id]?.status==='ok'?'Verbunden':'Wartet auf Daten')):'Ausgeblendet'}}</div><v-btn block variant="tonal" prepend-icon="mdi-tune" class="mt-5" @click="editWidget(w)">Konfigurieren</v-btn></v-card></div></template>
   <template v-if="tab==='monitors'"><v-alert variant="tonal" color="secondary" icon="mdi-information-outline" class="mb-6">Die Koordinaten bilden die gemeinsame Leinwand. Ordne in Electron jedem Monitor einen erkannten Bildschirm zu. Im Browser steht die Gesamtvorschau zur Verfügung.</v-alert><div class="monitor-editor"><v-card v-for="m in monitorDraft" :key="m.id" class="pa-6"><div class="d-flex justify-space-between"><v-icon icon="mdi-monitor" color="secondary" size="36"/><v-switch v-model="m.enabled" label="Aktiv" hide-details color="primary"/></div><v-text-field v-model="m.name" label="Name" class="mt-5"/><v-select :model-value="m.displayId" :items="wall.displays" item-title="name" item-value="id" label="Physischer Bildschirm" clearable @update:model-value="id=>assignDisplay(m,id||null)"/><div class="coordinate-grid"><v-text-field v-for="key in ['x','y','width','height']" :key="key" v-model.number="m[key]" type="number" :label="{x:'X',y:'Y',width:'Breite',height:'Höhe'}[key]" suffix="px"/></div></v-card></div><div class="d-flex ga-3 mt-6"><v-btn variant="tonal" prepend-icon="mdi-plus" :disabled="monitorDraft.length>=16" @click="addMonitor">Monitor hinzufügen</v-btn><v-btn color="primary" :loading="busy" prepend-icon="mdi-check" @click="saveMonitors">Layout speichern</v-btn></div></template>
   <template v-if="tab==='settings'&&settings"><div class="settings-grid"><v-card class="pa-7"><h2 class="mb-6">Wiedergabe</h2><v-text-field v-model="settings.name" label="Name der Bilderwand"/><div class="coordinate-grid"><v-text-field v-model.number="settings.intervalSeconds" label="Bildwechsel" type="number" suffix="Sekunden"/><v-text-field v-model.number="settings.fadeSeconds" label="Überblendung" type="number" suffix="Sekunden"/></div><p class="mb-3">Helligkeit · {{settings.brightness}} %</p><v-slider v-model="settings.brightness" min="10" max="100" step="1" color="primary" thumb-label/><v-switch v-model="settings.shuffle" label="Zufällige Auswahl nach Bildpriorität" color="primary"/><v-btn color="primary" prepend-icon="mdi-check" :loading="busy" @click="saveSettings">Einstellungen speichern</v-btn></v-card><div><v-card class="pa-7 mb-5"><h2>Mobile Fernsteuerung</h2><p class="muted my-4">Öffne diese Adresse auf deinem Smartphone im selben Netzwerk und melde dich mit dem Zugangscode an.</p><div v-for="address in wall.addresses" :key="address" class="address">{{address}}/admin</div><div v-if="!wall.addresses.length" class="muted">Kein Netzwerkinterface gefunden.</div><v-text-field :model-value="getToken()" label="Zugangscode" readonly type="password" class="mt-6"/><v-btn variant="tonal" prepend-icon="mdi-content-copy" @click="copyToken">Code kopieren</v-btn></v-card><v-card class="pa-7"><h2>JSON-Konfiguration</h2><p class="muted my-4">Exportiere Einstellungen und Medienreferenzen als Sicherung. Bilddateien und Zugangsdaten werden separat gespeichert.</p><div class="d-flex ga-3 flex-wrap"><v-btn variant="tonal" prepend-icon="mdi-download" @click="exportConfig">Exportieren</v-btn><v-btn tag="label" variant="tonal" prepend-icon="mdi-upload">Importieren<input hidden type="file" accept="application/json" @change="importConfig"></v-btn></div></v-card></div></div></template>
   <footer class="admin-footer"><span>Monitor Wall <span class="muted">/ Ein kleines Stück Zuhause.</span></span><span class="muted"><v-icon size="14" icon="mdi-folder-outline" class="mr-2"/>Lokal gespeichert · ohne Datenbank</span></footer>
  </div></v-main>
 </v-layout>
 <input ref="uploadInput" hidden type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,image/avif,.html,.htm" @change="upload">
 <v-dialog v-model="sceneDialog" max-width="700" scrollable><v-card><v-card-title class="pa-6">{{wall.config.scenes.some(s=>s.id===editing?.id)?'Szene bearbeiten':'Neue Szene'}}</v-card-title><v-card-text v-if="editing"><v-text-field v-model="editing.title" label="Titel"/><div class="coordinate-grid"><v-select v-model="editing.type" :items="types" label="Darstellung"/><v-text-field v-model="editing.category" label="Kategorie"/></div><GooglePhotosGallery v-if="editing.type==='google-photos'" :scene="editing" :saved="wall.config.scenes.some(s=>s.id===editing.id&&s.type==='google-photos')" @source="id=>editing.googlePhotos={mediaSourceId:id}"/><v-textarea v-if="editing.type!=='google-photos'" v-model="sourceText" label="Quellen · eine URL pro Zeile" rows="3" variant="outlined" placeholder="/media/datei.jpg oder https://…"/><v-btn v-if="editing.type!=='google-photos'" variant="tonal" prepend-icon="mdi-upload" :loading="busy" @click="chooseFiles('editing')">Dateien hinzufügen</v-btn><v-select v-model="editing.seasons" :items="seasons" label="Jahreszeiten · leer = ganzjährig" multiple chips class="mt-6"/><v-select v-model="editing.hours" :items="Array.from({length:24},(_,i)=>({title:`${i}:00 – ${i}:59`,value:i}))" label="Tagesstunden · leer = jederzeit" multiple chips/><div class="coordinate-grid"><v-select v-model="editing.weight" :items="[1,2,3,4,5]" label="Priorität"/><v-text-field v-model.number="editing.scrollSeconds" type="number" label="Panorama-Scrollzyklus" suffix="s"/></div><v-switch v-model="editing.enabled" color="primary" label="In der Wiedergabe verwenden" hide-details/><v-alert v-if="dialogError" color="error" variant="tonal" class="mt-4">{{dialogError}}</v-alert></v-card-text><v-card-actions class="pa-5"><v-btn v-if="wall.config.scenes.some(s=>s.id===editing?.id)" color="error" @click="deleteScene">Entfernen</v-btn><v-spacer/><v-btn @click="sceneDialog=false">Abbrechen</v-btn><v-btn color="primary" variant="flat" :loading="busy" @click="saveScene">Speichern</v-btn></v-card-actions></v-card></v-dialog>
 <v-dialog v-model="widgetDialog" max-width="720" scrollable><v-card><v-card-title class="pa-6">Informationsmodul konfigurieren</v-card-title><v-card-text v-if="widget"><v-text-field v-model="widget.title" label="Titel"/><v-select v-model="widget.type" :items="Object.keys(widgetIcons).map(type=>({value:type,title:{clock:'Datum & Uhrzeit',title:'Bildtitel',weather:'Wetter',transit:'Bus & Bahn',school:'Vertretungsplan',mpd:'MPD',calendar:'Google Kalender',cameras:'Kameras',soccer:'Fußball'}[type]}))" label="Modultyp"/><div class="coordinate-grid"><v-select v-model="widget.monitor" :items="wall.config.monitors" item-title="name" item-value="id" label="Monitor"/><v-select v-model="widget.position" :items="positions" label="Position"/></div><v-text-field v-model.number="widget.refreshSeconds" label="Aktualisierungsintervall" type="number" suffix="s"/><v-alert variant="tonal" color="secondary" class="mb-5">{{optionHelp[widget.type]}}</v-alert><v-textarea v-model="optionsText" label="Dienstoptionen (JSON)" rows="7" variant="outlined" class="code-input"/><v-expansion-panels variant="accordion"><v-expansion-panel title="Zugangsdaten"><v-expansion-panel-text><p class="muted mb-4">Werden nur geschrieben und niemals an die Oberfläche zurückgegeben. Leere Felder überschreiben vorhandene Werte. Unterstützt: password, authorization, clientId, clientSecret, refreshToken.</p><v-textarea v-model="secretText" label="Neue Zugangsdaten (JSON)" rows="4" variant="outlined" class="code-input"/></v-expansion-panel-text></v-expansion-panel></v-expansion-panels><v-switch v-model="widget.enabled" label="Auf der Bilderwand anzeigen" color="primary"/><v-alert v-if="dialogError" color="error" variant="tonal">{{dialogError}}</v-alert></v-card-text><v-card-actions class="pa-5"><v-spacer/><v-btn @click="widgetDialog=false">Abbrechen</v-btn><v-btn color="primary" variant="flat" :loading="busy" @click="saveWidget">Speichern</v-btn></v-card-actions></v-card></v-dialog>
 <v-snackbar :model-value="!!notice" timeout="2500" @update:model-value="notice=''">{{notice}}</v-snackbar>
</template>
