const {app,BrowserWindow}=require('electron');
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
app.on('window-all-closed',()=>{});
app.whenReady().then(async()=>{
 const {createWallServer}=await import('../server/app.js');
 const {fakeGoogle}=await import('../tests/fixtures/google-photos.js');
 const google=fakeGoogle();
 const directory=await fs.mkdtemp('/private/tmp/wall-electron-');
 let service,win;
 try{
 service=await createWallServer({directory,host:'127.0.0.1',port:0,dist:path.resolve(__dirname,'../dist'),photosOptions:{fetchImpl:google.fetchImpl,now:google.nowFn}});
 const config=structuredClone(service.store.config);config.widgets.forEach(w=>w.enabled=['clock','title'].includes(w.type));await service.store.update(config);
 const base=`http://127.0.0.1:${service.server.address().port}`;
 win=new BrowserWindow({width:1440,height:1080,show:false,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,offscreen:true,backgroundThrottling:false}});
 const errors=[];win.webContents.on('console-message',event=>{if(event.level==='error')errors.push(event.message);});
 await win.loadURL(`${base}/admin#token=${service.token}`);
 const run=code=>win.webContents.executeJavaScript(code);
 async function waitFor(code){const end=Date.now()+10000;while(Date.now()<end){if(await run(code))return;await new Promise(r=>setTimeout(r,100));}throw Error(`UI not ready: ${code}`);}
 await waitFor(`document.body.innerText.includes('Schön, zu Hause zu sein.')`);
 await new Promise(r=>setTimeout(r,700));
 assert.equal(await run(`document.querySelector('.sidebar').getBoundingClientRect().left>=0`),true,'Desktop navigation must be visible');
 await fs.writeFile('/private/tmp/monitor-wall-desktop.png',(await win.webContents.capturePage()).toPNG());
 await run(`Array.from(document.querySelectorAll('.v-list-item')).find(e=>e.innerText.includes('Mediathek')).click()`);
 await waitFor(`document.body.innerText.includes('Momente, die bleiben.')`);
 assert.equal(await run(`document.querySelectorAll('.media-card').length`),5);
 await run(`Array.from(document.querySelectorAll('button')).find(e=>e.innerText.includes('Szene hinzufügen')).click()`);
 await waitFor(`document.querySelector('.v-dialog.v-overlay--active')?.innerText.includes('Neue Szene')`);
 await run(`Array.from(document.querySelectorAll('.v-dialog.v-overlay--active button')).find(e=>e.innerText.includes('Abbrechen')).click()`);
 await waitFor(`!document.querySelector('.v-dialog.v-overlay--active')`);
 await new Promise(r=>setTimeout(r,400));
 await run(`Array.from(document.querySelectorAll('.v-list-item')).find(e=>e.innerText.includes('Informationen')).click()`);
 await waitFor(`document.querySelectorAll('.widget-grid>.v-card').length===9`);
 await run(`Array.from(document.querySelectorAll('button')).find(e=>e.innerText.includes('Konfigurieren')).click()`);
 await waitFor(`document.querySelector('.v-dialog.v-overlay--active')?.innerText.includes('Informationsmodul konfigurieren')`);
 await run(`Array.from(document.querySelectorAll('.v-dialog.v-overlay--active button')).find(e=>e.innerText.includes('Abbrechen')).click()`);
 await waitFor(`!document.querySelector('.v-dialog.v-overlay--active')`);
 await new Promise(r=>setTimeout(r,400));
 await run(`Array.from(document.querySelectorAll('.v-list-item')).find(e=>e.innerText.includes('Einstellungen')).click()`);
 await waitFor(`document.body.innerText.includes('Mobile Fernsteuerung')`);
 await run(`(()=>{const input=Array.from(document.querySelectorAll('input')).find(e=>e.value==='Unsere Bilderwand');input.value='Test Zuhause';input.dispatchEvent(new Event('input',{bubbles:true}));Array.from(document.querySelectorAll('button')).find(e=>e.innerText.includes('Einstellungen speichern')).click();})()`);
 await waitFor(`document.body.innerText.includes('Gespeichert')`);
 assert.equal(service.store.config.name,'Test Zuhause','Settings save must reach backend');
 await run(`Array.from(document.querySelectorAll('.v-list-item')).find(e=>e.innerText.includes('Übersicht')).click()`);
 await waitFor(`document.body.innerText.includes('Schön, zu Hause zu sein.')`);
 win.setSize(390,844);await new Promise(r=>setTimeout(r,500));
 await fs.writeFile('/private/tmp/monitor-wall-mobile.png',(await win.webContents.capturePage()).toPNG());
 assert.equal(await run(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Mobile horizontal overflow');
 await win.loadURL(`${base}/wall#token=${service.token}`);
 await waitFor(`document.querySelector('.wall-world')&&document.querySelector('.scene-layer')`);
 assert.equal(await run(`document.querySelectorAll('.monitor-overlay').length`),4);
 const galleryScene={id:'cloud-gallery',title:'Familienalbum aus Google',type:'google-photos',category:'Familie',sources:[],enabled:true,weight:3,seasons:[],hours:[],scrollSeconds:90};
 await service.store.update({...service.store.config,scenes:[...service.store.config.scenes,galleryScene]});
 await service.store.updateSecrets(s=>({...s,googlePhotos:{clientId:'test.apps.googleusercontent.com',clientSecret:'private-client',refreshToken:'private-refresh'}}));
 await service.photos.connectScene(galleryScene);await service.photos.refresh(galleryScene);service.broadcast();
 await run(`fetch('/api/control',{method:'POST',headers:{Authorization:'Bearer ${service.token}','Content-Type':'application/json'},body:JSON.stringify({action:'select',id:'cloud-gallery'})}).then(r=>r.json())`);
 await waitFor(`document.querySelectorAll('.stack-monitor').length===4&&document.querySelectorAll('.stack-monitor img').length===28`);
 await waitFor(`Array.from(document.querySelectorAll('.stack-monitor img')).every(img=>img.complete&&img.naturalWidth>0)`);
 await win.loadURL(`${base}/admin#token=${service.token}`);
 await waitFor(`document.body.innerText.includes('Schön, zu Hause zu sein.')`);
 await run(`Array.from(document.querySelectorAll('.v-list-item')).find(e=>e.innerText.includes('Mediathek')).click()`);
 await waitFor(`document.querySelectorAll('.media-card').length===6`);
 await run(`Array.from(document.querySelectorAll('.media-card')).find(e=>e.innerText.includes('Familienalbum aus Google')).querySelector('.media-image').click()`);
 await waitFor(`document.querySelector('.google-gallery')?.innerText.includes('Alben bei Google auswählen')`);
 await new Promise(r=>setTimeout(r,500));
 await fs.writeFile('/private/tmp/monitor-wall-google-gallery.png',(await win.webContents.capturePage()).toPNG());

 assert.deepEqual(errors,[]);
 console.log('Electron UI smoke passed: desktop, mobile, media, widget dialog, settings, wall, Google Photos gallery and image stack.');
 }finally{win?.destroy();await service?.close();await fs.rm(directory,{recursive:true,force:true});}
 app.quit();
}).catch(error=>{console.error(error);app.exit(1);});
